/**
 * Bibelbuchnamen und -kuerzel je Sprache — Quelle: die Neue-Welt-Uebersetzung
 * auf jw.org (Buecheruebersicht, positionsweise uebernommen; die Reihenfolge
 * der 66 Buecher ist in jeder Sprache dieselbe).
 *
 * Hier stand frueher genau EIN Buch: "Jeremia", das Buch der Demo-Woche. Alle
 * anderen 65 blieben in jeder Sprache deutsch stehen.
 *
 * Form: pipe-getrennte Listen in kanonischer Reihenfolge statt Objekte. Als
 * Objekte stuende derselbe deutsche Schluessel 33-mal im Bundle; so kostet die
 * volle Abdeckung nur einen Bruchteil. Die Zuordnung baut buchTabelle() beim
 * ersten Gebrauch und merkt sie sich.
 *
 * Erzeugt von scratchpad/gen-books.mjs — nicht von Hand pflegen.
 */

/** Die 66 Buecher auf Deutsch, kanonische Reihenfolge (Bezugsliste). */
const DE_VOLL = "1. Mose|2. Mose|3. Mose|4. Mose|5. Mose|Josua|Richter|Ruth|1. Samuel|2. Samuel|1. Könige|2. Könige|1. Chronika|2. Chronika|Esra|Nehemia|Esther|Hiob|Psalmen|Sprüche|Prediger|Hohes Lied|Jesaja|Jeremia|Klagelieder|Hesekiel|Daniel|Hosea|Joel|Amos|Obadja|Jona|Micha|Nahum|Habakuk|Zephanja|Haggai|Sacharja|Maleachi|Matthäus|Markus|Lukas|Johannes|Apostelgeschichte|Römer|1. Korinther|2. Korinther|Galater|Epheser|Philipper|Kolosser|1. Thessalonicher|2. Thessalonicher|1. Timotheus|2. Timotheus|Titus|Philemon|Hebräer|Jakobus|1. Petrus|2. Petrus|1. Johannes|2. Johannes|3. Johannes|Judas|Offenbarung"

/** Dieselben Buecher als Kuerzel ("1Mo", "Jer" …). */
const DE_KURZ = "1Mo|2Mo|3Mo|4Mo|5Mo|Jos|Ri|Ru|1Sa|2Sa|1Kö|2Kö|1Ch|2Ch|Esr|Ne|Est|Hi|Ps|Spr|Pr|Hoh|Jes|Jer|Klg|Hes|Da|Hos|Joel|Am|Ob|Jon|Mi|Nah|Hab|Ze|Hag|Sach|Mal|Mat|Mar|Luk|Joh|Apg|Rö|1Ko|2Ko|Gal|Eph|Php|Kol|1Th|2Th|1Ti|2Ti|Tit|Phm|Heb|Jak|1Pe|2Pe|1Jo|2Jo|3Jo|Jud|Off"

/**
 * Urdu hat die Uebersetzung erst teilweise; diese neun Buecher fehlen dort und
 * werden aus der Bezugsliste genommen, damit die Positionen wieder passen.
 */
const UR_FEHLEN = "3. Mose|4. Mose|5. Mose|Josua|Richter|Zephanja|Haggai|Sacharja|Maleachi"

/** Sprachcode -> [Namen, Kuerzel], je pipe-getrennt in kanonischer Reihenfolge. */
const ZIEL: Record<string, [string, string]> = {
  en: ["Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|1 Samuel|2 Samuel|1 Kings|2 Kings|1 Chronicles|2 Chronicles|Ezra|Nehemiah|Esther|Job|Psalms|Proverbs|Ecclesiastes|Song of Solomon|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|1 Corinthians|2 Corinthians|Galatians|Ephesians|Philippians|Colossians|1 Thessalonians|2 Thessalonians|1 Timothy|2 Timothy|Titus|Philemon|Hebrews|James|1 Peter|2 Peter|1 John|2 John|3 John|Jude|Revelation", "Ge|Ex|Le|Nu|De|Jos|Jg|Ru|1Sa|2Sa|1Ki|2Ki|1Ch|2Ch|Ezr|Ne|Es|Job|Ps|Pr|Ec|Ca|Isa|Jer|La|Eze|Da|Ho|Joe|Am|Ob|Jon|Mic|Na|Hab|Zep|Hag|Zec|Mal|Mt|Mr|Lu|Joh|Ac|Ro|1Co|2Co|Ga|Eph|Php|Col|1Th|2Th|1Ti|2Ti|Tit|Phm|Heb|Jas|1Pe|2Pe|1Jo|2Jo|3Jo|Jude|Re"],
  es: ["Génesis|Éxodo|Levítico|Números|Deuteronomio|Josué|Jueces|Rut|1 Samuel|2 Samuel|1 Reyes|2 Reyes|1 Crónicas|2 Crónicas|Esdras|Nehemías|Ester|Job|Salmos|Proverbios|Eclesiastés|El Cantar de los Cantares|Isaías|Jeremías|Lamentaciones|Ezequiel|Daniel|Oseas|Joel|Amós|Abdías|Jonás|Miqueas|Nahúm|Habacuc|Sofonías|Ageo|Zacarías|Malaquías|Mateo|Marcos|Lucas|Juan|Hechos|Romanos|1 Corintios|2 Corintios|Gálatas|Efesios|Filipenses|Colosenses|1 Tesalonicenses|2 Tesalonicenses|1 Timoteo|2 Timoteo|Tito|Filemón|Hebreos|Santiago|1 Pedro|2 Pedro|1 Juan|2 Juan|3 Juan|Judas|Apocalipsis", "Gé|Éx|Le|Nú|Dt|Jos|Jue|Rut|1Sa|2Sa|1Re|2Re|1Cr|2Cr|Esd|Ne|Est|Job|Sl|Pr|Ec|Can|Is|Jer|Lam|Eze|Da|Os|Joe|Am|Abd|Jon|Miq|Na|Hab|Sof|Ag|Zac|Mal|Mt|Mr|Lu|Jn|Hch|Ro|1Co|2Co|Gál|Ef|Flp|Col|1Te|2Te|1Ti|2Ti|Tit|Flm|Heb|Snt|1Pe|2Pe|1Jn|2Jn|3Jn|Jud|Ap"],
  fr: ["Genèse|Exode|Lévitique|Nombres|Deutéronome|Josué|Juges|Ruth|1 Samuel|2 Samuel|1 Rois|2 Rois|1 Chroniques|2 Chroniques|Esdras|Néhémie|Esther|Job|Psaumes|Proverbes|Ecclésiaste|Chant de Salomon|Isaïe|Jérémie|Lamentations|Ézéchiel|Daniel|Osée|Joël|Amos|Abdias|Jonas|Michée|Nahum|Habacuc|Sophonie|Aggée|Zacharie|Malachie|Matthieu|Marc|Luc|Jean|Actes|Romains|1 Corinthiens|2 Corinthiens|Galates|Éphésiens|Philippiens|Colossiens|1 Thessaloniciens|2 Thessaloniciens|1 Timothée|2 Timothée|Tite|Philémon|Hébreux|Jacques|1 Pierre|2 Pierre|1 Jean|2 Jean|3 Jean|Jude|Révélation", "Gn|Ex|Lv|Nb|Dt|Jos|Jg|Ru|1S|2S|1R|2R|1Ch|2Ch|Esd|Né|Est|Jb|Ps|Pr|Ec|Ct|Is|Jr|Lm|Éz|Dn|Os|Jl|Am|Ab|Jon|Mi|Na|Hab|Sph|Ag|Za|Ml|Mt|Mc|Lc|Jean|Ac|Rm|1Co|2Co|Ga|Éph|Php|Col|1Th|2Th|1Tm|2Tm|Tt|Phm|Hé|Jc|1P|2P|1J|2J|3J|Jude|Ré"],
  it: ["Genesi|Esodo|Levitico|Numeri|Deuteronomio|Giosuè|Giudici|Rut|1 Samuele|2 Samuele|1 Re|2 Re|1 Cronache|2 Cronache|Esdra|Neemia|Ester|Giobbe|Salmi|Proverbi|Ecclesiaste|Cantico dei Cantici|Isaia|Geremia|Lamentazioni|Ezechiele|Daniele|Osea|Gioele|Amos|Abdia|Giona|Michea|Naum|Abacuc|Sofonia|Aggeo|Zaccaria|Malachia|Matteo|Marco|Luca|Giovanni|Atti|Romani|1 Corinti|2 Corinti|Galati|Efesini|Filippesi|Colossesi|1 Tessalonicesi|2 Tessalonicesi|1 Timoteo|2 Timoteo|Tito|Filemone|Ebrei|Giacomo|1 Pietro|2 Pietro|1 Giovanni|2 Giovanni|3 Giovanni|Giuda|Rivelazione", "Gen|Eso|Le|Nu|De|Gsè|Gdc|Ru|1Sa|2Sa|1Re|2Re|1Cr|2Cr|Esd|Ne|Est|Gb|Sl|Pr|Ec|Ca|Isa|Ger|La|Ez|Da|Os|Gle|Am|Abd|Gna|Mic|Na|Aba|Sof|Ag|Zac|Mal|Mt|Mr|Lu|Gv|At|Ro|1Co|2Co|Gal|Ef|Flp|Col|1Ts|2Ts|1Tm|2Tm|Tit|Flm|Eb|Gc|1Pt|2Pt|1Gv|2Gv|3Gv|Gda|Ri"],
  pt: ["Gênesis|Êxodo|Levítico|Números|Deuteronômio|Josué|Juízes|Rute|1 Samuel|2 Samuel|1 Reis|2 Reis|1 Crônicas|2 Crônicas|Esdras|Neemias|Ester|Jó|Salmos|Provérbios|Eclesiastes|Cântico de Salomão|Isaías|Jeremias|Lamentações|Ezequiel|Daniel|Oseias|Joel|Amós|Obadias|Jonas|Miqueias|Naum|Habacuque|Sofonias|Ageu|Zacarias|Malaquias|Mateus|Marcos|Lucas|João|Atos|Romanos|1 Coríntios|2 Coríntios|Gálatas|Efésios|Filipenses|Colossenses|1 Tessalonicenses|2 Tessalonicenses|1 Timóteo|2 Timóteo|Tito|Filêmon|Hebreus|Tiago|1 Pedro|2 Pedro|1 João|2 João|3 João|Judas|Apocalipse", "Gên|Êx|Le|Núm|De|Jos|Jz|Ru|1Sa|2Sa|1Rs|2Rs|1Cr|2Cr|Esd|Ne|Est|Jó|Sal|Pr|Ec|Cân|Is|Je|La|Ez|Da|Os|Jl|Am|Ob|Jon|Miq|Na|Hab|Sof|Ag|Za|Mal|Mt|Mr|Lu|Jo|At|Ro|1Co|2Co|Gál|Ef|Fil|Col|1Te|2Te|1Ti|2Ti|Tit|Flm|He|Tg|1Pe|2Pe|1Jo|2Jo|3Jo|Ju|Ap"],
  nl: ["Genesis|Exodus|Leviticus|Numeri|Deuteronomium|Jozua|Rechters|Ruth|1 Samuël|2 Samuël|1 Koningen|2 Koningen|1 Kronieken|2 Kronieken|Ezra|Nehemia|Esther|Job|Psalmen|Spreuken|Prediker|Hooglied|Jesaja|Jeremia|Klaagliederen|Ezechiël|Daniël|Hosea|Joël|Amos|Obadja|Jona|Micha|Nahum|Habakuk|Zefanja|Haggaï|Zacharia|Maleachi|Mattheüs|Markus|Lukas|Johannes|Handelingen|Romeinen|1 Korinthiërs|2 Korinthiërs|Galaten|Efeziërs|Filippenzen|Kolossenzen|1 Thessalonicenzen|2 Thessalonicenzen|1 Timotheüs|2 Timotheüs|Titus|Filemon|Hebreeën|Jakobus|1 Petrus|2 Petrus|1 Johannes|2 Johannes|3 Johannes|Judas|Openbaring", "Ge|Ex|Le|Nu|De|Joz|Re|Ru|1Sa|2Sa|1Kon|2Kon|1Kr|2Kr|Ezr|Ne|Es|Job|Ps|Sp|Pr|Hgl|Jes|Jer|Klg|Ez|Da|Ho|Joë|Am|Ob|Jon|Mi|Na|Hab|Ze|Hag|Za|Mal|Mt|Mr|Lu|Jo|Han|Ro|1Kor|2Kor|Ga|Ef|Fil|Kol|1Th|2Th|1Ti|2Ti|Tit|Flm|Heb|Jak|1Pe|2Pe|1Jo|2Jo|3Jo|Ju|Opb"],
  pl: ["Rodzaju|Wyjścia|Kapłańska|Liczb|Powtórzonego Prawa|Jozuego|Sędziów|Rut|1 Samuela|2 Samuela|1 Królów|2 Królów|1 Kronik|2 Kronik|Ezdrasza|Nehemiasza|Estery|Hioba|Psalmy|Przysłów|Kaznodziei|Pieśń|Izajasza|Jeremiasza|Lamentacje|Ezechiela|Daniela|Ozeasza|Joela|Amosa|Abdiasza|Jonasza|Micheasza|Nahuma|Habakuka|Sofoniasza|Aggeusza|Zachariasza|Malachiasza|Mateusza|Marka|Łukasza|Jana|Dzieje|Rzymian|1 Koryntian|2 Koryntian|Galatów|Efezjan|Filipian|Kolosan|1 Tesaloniczan|2 Tesaloniczan|1 Tymoteusza|2 Tymoteusza|Tytusa|Filemona|Hebrajczyków|Jakuba|1 Piotra|2 Piotra|1 Jana|2 Jana|3 Jana|Judy|Objawienie", "Rdz|Wj|Kpł|Lb|Pwt|Joz|Sdz|Rut|1Sm|2Sm|1Kl|2Kl|1Kn|2Kn|Ezd|Neh|Est|Hi|Ps|Prz|Kzn|PnP|Iz|Jer|Lam|Eze|Dn|Oz|Jl|Am|Abd|Jon|Mi|Nah|Hab|Sof|Ag|Za|Mal|Mt|Mk|Łk|Jn|Dz|Rz|1Ko|2Ko|Gal|Ef|Flp|Kol|1Ts|2Ts|1Tm|2Tm|Tyt|Flm|Heb|Jak|1Pt|2Pt|1Jn|2Jn|3Jn|Judy|Obj"],
  ru: ["Бытие|Исход|Левит|Числа|Второзаконие|Иисус Навин|Судей|Руфь|1 Самуила|2 Самуила|1 Царей|2 Царей|1 Летопись|2 Летопись|Ездра|Неемия|Эсфирь|Иов|Псалмы|Притчи|Экклезиаст|Песня Соломона|Исайя|Иеремия|Плач Иеремии|Иезекииль|Даниил|Осия|Иоиль|Амос|Авдий|Иона|Михей|Наум|Аввакум|Софония|Аггей|Захария|Малахия|Матфея|Марка|Луки|Иоанна|Деяния|Римлянам|1 Коринфянам|2 Коринфянам|Галатам|Эфесянам|Филиппийцам|Колоссянам|1 Фессалоникийцам|2 Фессалоникийцам|1 Тимофею|2 Тимофею|Титу|Филимону|Евреям|Иакова|1 Петра|2 Петра|1 Иоанна|2 Иоанна|3 Иоанна|Иуды|Откровение", "Бт|Исх|Лв|Чс|Вт|ИсН|Сд|Рф|1См|2См|1Цр|2Цр|1Лт|2Лт|Езд|Не|Эсф|Иов|Пс|Пр|Эк|Псн|Иса|Иер|Пл|Иез|Дан|Ос|Ил|Ам|Авд|Ион|Мх|На|Авв|Сф|Аг|Зх|Мл|Мф|Мк|Лк|Ин|Де|Рм|1Кр|2Кр|Гл|Эф|Фп|Кл|1Фс|2Фс|1Тм|2Тм|Тит|Фм|Евр|Иак|1Пт|2Пт|1Ин|2Ин|3Ин|Иуды|Отк"],
  uk: ["Буття|Вихід|Левіт|Числа|Повторення Закону|Ісуса Навина|Суддів|Рут|1 Самуїла|2 Самуїла|1 Царів|2 Царів|1 Хронік|2 Хронік|Ездри|Неемії|Естер|Йова|Псалми|Прислів’я|Екклезіаста|Пісня над піснями|Ісаї|Єремії|Плач Єремії|Єзекіїля|Даниїла|Осії|Йоіла|Амоса|Овдія|Йони|Михея|Наума|Авакума|Софонії|Огія|Захарія|Малахії|Матвія|Марка|Луки|Івана|Дії|Римлян|1 Коринфян|2 Коринфян|Галатів|Ефесян|Філіппійців|Колоссян|1 Фессалонікійців|2 Фессалонікійців|1 Тимофія|2 Тимофія|Тита|Филимона|Євреїв|Якова|1 Петра|2 Петра|1 Івана|2 Івана|3 Івана|Юди|Об’явлення", "Бт|Вх|Лв|Чс|Пв|ІсН|Сд|Рт|1См|2См|1Цр|2Цр|1Хр|2Хр|Езд|Не|Ес|Йв|Пс|Пр|Ек|Псн|Іс|Єр|Пл|Єз|Дн|Ос|Йл|Ам|Ов|Йн|Мих|На|Ав|Сф|Ог|Зх|Мл|Мт|Мр|Лк|Ів|Дії|Рм|1Кр|2Кр|Гл|Еф|Флп|Кл|1Фс|2Фс|1Тм|2Тм|Тит|Флм|Єв|Як|1Пт|2Пт|1Ів|2Ів|3Ів|Юд|Об"],
  ro: ["Geneza|Exodul|Leviticul|Numerele|Deuteronomul|Iosua|Judecătorii|Rut|1 Samuel|2 Samuel|1 Regi|2 Regi|1 Cronici|2 Cronici|Ezra|Neemia|Estera|Iov|Psalmii|Proverbele|Eclesiastul|Cântarea cântărilor|Isaia|Ieremia|Plângerile|Ezechiel|Daniel|Osea|Ioel|Amos|Obadia|Iona|Mica|Naum|Habacuc|Țefania|Hagai|Zaharia|Maleahi|Matei|Marcu|Luca|Ioan|Faptele|Romani|1 Corinteni|2 Corinteni|Galateni|Efeseni|Filipeni|Coloseni|1 Tesaloniceni|2 Tesaloniceni|1 Timotei|2 Timotei|Tit|Filimon|Evrei|Iacov|1 Petru|2 Petru|1 Ioan|2 Ioan|3 Ioan|Iuda|Revelația", "Ge|Ex|Le|Nu|De|Ios|Ju|Rut|1Sa|2Sa|1Re|2Re|1Cr|2Cr|Ezr|Ne|Es|Iov|Ps|Pr|Ec|Cân|Is|Ier|Pln|Eze|Da|Os|Ioe|Am|Ob|Ion|Mi|Na|Hab|Țe|Hag|Za|Mal|Mt|Mr|Lu|Ioa|Fa|Ro|1Co|2Co|Ga|Ef|Flp|Col|1Te|2Te|1Ti|2Ti|Tit|Flm|Ev|Iac|1Pe|2Pe|1Io|2Io|3Io|Iuda|Re"],
  el: ["Γένεση|Έξοδος|Λευιτικό|Αριθμοί|Δευτερονόμιο|Ιησούς του Ναυή|Κριτές|Ρουθ|1 Σαμουήλ|2 Σαμουήλ|1 Βασιλέων|2 Βασιλέων|1 Χρονικών|2 Χρονικών|Έσδρας|Νεεμίας|Εσθήρ|Ιώβ|Ψαλμοί|Παροιμίες|Εκκλησιαστής|Άσμα Ασμάτων|Ησαΐας|Ιερεμίας|Θρήνοι|Ιεζεκιήλ|Δανιήλ|Ωσηέ|Ιωήλ|Αμώς|Αβδιού|Ιωνάς|Μιχαίας|Ναούμ|Αββακούμ|Σοφονίας|Αγγαίος|Ζαχαρίας|Μαλαχίας|Ματθαίος|Μάρκος|Λουκάς|Ιωάννης|Πράξεις|Ρωμαίους|1 Κορινθίους|2 Κορινθίους|Γαλάτες|Εφεσίους|Φιλιππησίους|Κολοσσαείς|1 Θεσσαλονικείς|2 Θεσσαλονικείς|1 Τιμόθεο|2 Τιμόθεο|Τίτο|Φιλήμονα|Εβραίους|Ιακώβου|1 Πέτρου|2 Πέτρου|1 Ιωάννη|2 Ιωάννη|3 Ιωάννη|Ιούδα|Αποκάλυψη", "Γε|Εξ|Λευ|Αρ|Δευ|Ιη|Κρ|Ρθ|1Σα|2Σα|1Βα|2Βα|1Χρ|2Χρ|Εσδ|Νε|Εσθ|Ιώβ|Ψλ|Παρ|Εκ|Ασμ|Ησ|Ιερ|Θρ|Ιεζ|Δα|Ωσ|Ιωλ|Αμ|Αβδ|Ιων|Μιχ|Να|Αββ|Σοφ|Αγγ|Ζαχ|Μαλ|Ματ|Μαρ|Λου|Ιωα|Πρ|Ρω|1Κο|2Κο|Γα|Εφ|Φλπ|Κολ|1Θε|2Θε|1Τι|2Τι|Τιτ|Φλμ|Εβρ|Ιακ|1Πε|2Πε|1Ιω|2Ιω|3Ιω|Ιου|Απ"],
  cs: ["1. Mojžíšova|2. Mojžíšova|3. Mojžíšova|4. Mojžíšova|5. Mojžíšova|Jozue|Soudci|Rut|1. Samuelova|2. Samuelova|1. Královská|2. Královská|1. Paralipomenon|2. Paralipomenon|Ezra|Nehemjáš|Ester|Job|Žalmy|Přísloví|Kazatel|Šalomounova píseň|Izajáš|Jeremjáš|Nářky|Ezekiel|Daniel|Ozeáš|Joel|Amos|Obadjáš|Jonáš|Micheáš|Nahum|Habakuk|Sefanjáš|Ageus|Zecharjáš|Malachiáš|Matouš|Marek|Lukáš|Jan|Skutky|Římanům|1. Korinťanům|2. Korinťanům|Galaťanům|Efezanům|Filipanům|Kolosanům|1. Tesaloničanům|2. Tesaloničanům|1. Timoteovi|2. Timoteovi|Titovi|Filemonovi|Hebrejcům|Jakub|1. Petra|2. Petra|1. Jana|2. Jana|3. Jana|Juda|Zjevení", "1Mo|2Mo|3Mo|4Mo|5Mo|Joz|Sd|Rut|1Sa|2Sa|1Kr|2Kr|1Pa|2Pa|Ezr|Ne|Es|Job|Ža|Př|Ka|Pís|Iz|Jer|Ná|Eze|Da|Oz|Joe|Am|Ob|Jon|Mi|Na|Hab|Sef|Ag|Ze|Mal|Mt|Mr|Lk|Jan|Sk|Ří|1Ko|2Ko|Ga|Ef|Flp|Kol|1Te|2Te|1Ti|2Ti|Tit|Flm|Heb|Jk|1Pe|2Pe|1Ja|2Ja|3Ja|Juda|Zj"],
  sk: ["1. Mojžišova|2. Mojžišova|3. Mojžišova|4. Mojžišova|5. Mojžišova|Jozua|Sudcovia|Rút|1. Samuelova|2. Samuelova|1. Kráľov|2. Kráľov|1. Kroník|2. Kroník|Ezdráš|Nehemiáš|Ester|Jób|Kniha žalmov|Príslovia|Kazateľ|Šalamúnova pieseň|Izaiáš|Jeremiáš|Plač Jeremiáša|Ezechiel|Daniel|Ozeáš|Joel|Amos|Abdiáš|Jonáš|Micheáš|Náhum|Habakuk|Sofoniáš|Aggeus|Zachariáš|Malachiáš|Matúš|Marek|Lukáš|Ján|Skutky|Rimanom|1. Korinťanom|2. Korinťanom|Galaťanom|Efezanom|Filipanom|Kolosanom|1. Tesaloničanom|2. Tesaloničanom|1. Timotejovi|2. Timotejovi|Títovi|Filemonovi|Hebrejom|Jakub|1. Petra|2. Petra|1. Jána|2. Jána|3. Jána|Júda|Zjavenie", "1Mo|2Mo|3Mo|4Mo|5Mo|Joz|Sud|Rút|1Sa|2Sa|1Kr|2Kr|1Kn|2Kn|Ezd|Neh|Est|Jób|Ža|Prí|Kaz|Pie|Iz|Jer|Pla|Eze|Dan|Oz|Joe|Am|Ab|Jon|Mi|Náh|Hab|Sof|Ag|Za|Mal|Mat|Mar|Luk|Ján|Sk|Rim|1Ko|2Ko|Gal|Ef|Fil|Kol|1Te|2Te|1Ti|2Ti|Tít|Fm|Heb|Jak|1Pe|2Pe|1Já|2Já|3Já|Jú|Zj"],
  hu: ["1Mózes|2Mózes|3Mózes|4Mózes|5Mózes|Józsué|Bírák|Ruth|1Sámuel|2Sámuel|1Királyok|2Királyok|1Krónikák|2Krónikák|Ezsdrás|Nehémiás|Eszter|Jób|Zsoltárok|Példabeszédek|Prédikátor|Énekek éneke|Ézsaiás|Jeremiás|Siralmak|Ezékiel|Dániel|Hóseás|Jóel|Ámós|Abdiás|Jónás|Mikeás|Náhum|Habakuk|Sofóniás|Aggeus|Zakariás|Malakiás|Máté|Márk|Lukács|János|Cselekedetek|Róma|1Korintusz|2Korintusz|Galácia|Efézus|Filippi|Kolosszé|1Tesszalonika|2Tesszalonika|1Timóteusz|2Timóteusz|Titusz|Filemon|Héberek|Jakab|1Péter|2Péter|1János|2János|3János|Júdás|Jelenések", "1Mó|2Mó|3Mó|4Mó|5Mó|Jzs|Bí|Ru|1Sá|2Sá|1Ki|2Ki|1Kr|2Kr|Ezs|Ne|Esz|Jób|Zs|Pl|Pr|Én|Ézs|Jr|Si|Ez|Dá|Hó|Jóe|Ám|Ab|Jón|Mi|Ná|Ha|So|Ag|Za|Ma|Mt|Mr|Lk|Jn|Cs|Ró|1Ko|2Ko|Ga|Ef|Flp|Kol|1Te|2Te|1Ti|2Ti|Tit|Flm|Héb|Jk|1Pt|2Pt|1Jn|2Jn|3Jn|Júd|Jel"],
  hr: ["Postanak|Izlazak|Levitski zakonik|Brojevi|Ponovljeni zakon|Jošua|Suci|Ruta|1. Samuelova|2. Samuelova|1. Kraljevima|2. Kraljevima|1. Ljetopisa|2. Ljetopisa|Ezra|Nehemija|Estera|Job|Psalmi|Mudre izreke|Propovjednik|Pjesma nad pjesmama|Izaija|Jeremija|Tužaljke|Ezekijel|Danijel|Hošea|Joel|Amos|Obadija|Jona|Mihej|Nahum|Habakuk|Sefanija|Hagaj|Zaharija|Malahija|Matej|Marko|Luka|Ivan|Djela apostolska|Rimljanima|1. Korinćanima|2. Korinćanima|Galaćanima|Efežanima|Filipljanima|Kološanima|1. Solunjanima|2. Solunjanima|1. Timoteju|2. Timoteju|Titu|Filemonu|Hebrejima|Jakov|1. Petrova|2. Petrova|1. Ivanova|2. Ivanova|3. Ivanova|Juda|Otkrivenje", "Pos|Izl|Le|Br|Pnz|Jš|Su|Ru|1Sa|2Sa|1Kr|2Kr|1Lje|2Lje|Ezr|Ne|Es|Job|Ps|Izr|Pr|Pj|Iza|Jr|Tu|Eze|Da|Ho|Jl|Am|Ob|Jn|Mi|Na|Hb|Sf|Hg|Za|Ml|Mt|Mk|Lk|Iv|Dj|Ri|1Ko|2Ko|Ga|Ef|Flp|Kol|1So|2So|1Ti|2Ti|Tit|Flm|He|Jk|1Pe|2Pe|1Iv|2Iv|3Iv|Jd|Ot"],
  sr: ["Postanak|Izlazak|Levitska|Brojevi|Ponovljeni zakoni|Isus Navin|Sudije|Ruta|1. Samuilova|2. Samuilova|1. Kraljevima|2. Kraljevima|1. Letopisa|2. Letopisa|Jezdra|Nemija|Jestira|Jov|Psalmi|Poslovice|Propovednik|Pesma nad pesmama|Isaija|Jeremija|Tužbalice|Jezekilj|Danilo|Osija|Joilo|Amos|Avdija|Jona|Mihej|Naum|Avakum|Sofonija|Agej|Zaharija|Malahija|Matej|Marko|Luka|Jovan|Dela apostolska|Rimljanima|1. Korinćanima|2. Korinćanima|Galatima|Efešanima|Filipljanima|Kološanima|1. Solunjanima|2. Solunjanima|1. Timoteju|2. Timoteju|Titu|Filimonu|Jevrejima|Jakovljeva|1. Petrova|2. Petrova|1. Jovanova|2. Jovanova|3. Jovanova|Judina|Otkrivenje", "Pst|Iz|Le|Br|Pz|IN|Su|Ru|1Sa|2Sa|1Kr|2Kr|1Le|2Le|Jzd|Ne|Jes|Jov|Ps|Psl|Pro|Pes|Is|Jer|Tu|Jzk|Da|Os|Jl|Am|Avd|Jon|Mi|Na|Avk|So|Ag|Za|Mal|Mt|Mr|Lu|Jv|Del|Ri|1Ko|2Ko|Ga|Ef|Fp|Ko|1So|2So|1Ti|2Ti|Ti|Fm|Jev|Ja|1Pe|2Pe|1Jv|2Jv|3Jv|Ju|Ot"],
  bg: ["Битие|Изход|Левит|Числа|Второзаконие|Исус Навиев|Съдии|Рут|1 Царе|2 Царе|3 Царе|4 Царе|1 Летописи|2 Летописи|Ездра|Неемия|Естир|Йов|Псалми|Притчи|Еклисиаст|Песен на песните|Исаия|Йеремия|Плачът на Йеремия|Езекиил|Даниил|Осия|Йоил|Амос|Авдия|Йона|Михей|Наум|Авакум|Софония|Агей|Захария|Малахия|Матей|Марко|Лука|Йоан|Деяния|Римляни|1 Коринтяни|2 Коринтяни|Галатяни|Ефесяни|Филипяни|Колосяни|1 Солунци|2 Солунци|1 Тимотей|2 Тимотей|Тит|Филимон|Евреи|Яков|1 Петър|2 Петър|1 Йоан|2 Йоан|3 Йоан|Юда|Откровение", "Би|Из|Ле|Чи|Вт|ИсН|Съд|Рут|1Ца|2Ца|3Ца|4Ца|1Ле|2Ле|Езд|Не|Ест|Йов|Пс|Пр|Ек|Псн|Иса|Йер|Плч|Езе|Да|Ос|Йл|Ам|Авд|Йон|Мих|На|Ава|Соф|Аг|Зах|Мал|Мт|Мр|Лу|Йоа|Де|Ри|1Ко|2Ко|Га|Еф|Флп|Кол|1Со|2Со|1Ти|2Ти|Тит|Флм|Ев|Як|1Пе|2Пе|1Йо|2Йо|3Йо|Юда|Отк"],
  sv: ["1 Moseboken|2 Moseboken|3 Moseboken|4 Moseboken|5 Moseboken|Josua|Domarboken|Rut|1 Samuelsboken|2 Samuelsboken|1 Kungaboken|2 Kungaboken|1 Krönikeboken|2 Krönikeboken|Esra|Nehemja|Ester|Job|Psalmerna|Ordspråksboken|Predikaren|Höga visan|Jesaja|Jeremia|Klagovisorna|Hesekiel|Daniel|Hosea|Joel|Amos|Obadja|Jona|Mika|Nahum|Habackuk|Sefanja|Haggaj|Sakarja|Malaki|Matteus|Markus|Lukas|Johannes|Apostlagärningarna|Romarna|1 Korinthierna|2 Korinthierna|Galaterna|Efesierna|Filipperna|Kolosserna|1 Thessalonikerna|2 Thessalonikerna|1 Timoteus|2 Timoteus|Titus|Filemon|Hebréerna|Jakob|1 Petrus|2 Petrus|1 Johannes|2 Johannes|3 Johannes|Judas|Uppenbarelseboken", "1Mo|2Mo|3Mo|4Mo|5Mo|Jos|Dom|Rut|1Sa|2Sa|1Ku|2Ku|1Kr|2Kr|Esr|Neh|Est|Job|Ps|Ord|Pre|HV|Jes|Jer|Klag|Hes|Dan|Hos|Joel|Am|Ob|Jon|Mik|Nah|Hab|Sef|Hag|Sak|Mal|Mt|Mk|Lu|Joh|Apg|Rom|1Kor|2Kor|Gal|Ef|Flp|Kol|1Th|2Th|1Ti|2Ti|Tit|Flm|Heb|Jak|1Pe|2Pe|1Jo|2Jo|3Jo|Jud|Upp"],
  da: ["1. Mosebog|2. Mosebog|3. Mosebog|4. Mosebog|5. Mosebog|Josva|Dommerne|Ruth|1. Samuel|2. Samuel|1. Kongebog|2. Kongebog|1. Krønikebog|2. Krønikebog|Ezra|Nehemias|Ester|Job|Salmerne|Ordsprogene|Prædikeren|Højsangen|Esajas|Jeremias|Klagesangene|Ezekiel|Daniel|Hoseas|Joel|Amos|Obadias|Jonas|Mika|Nahum|Habakkuk|Sefanias|Haggaj|Zakarias|Malakias|Matthæus|Markus|Lukas|Johannes|Apostlenes Gerninger|Romerne|1. Korinther|2. Korinther|Galaterne|Efeserne|Filipperne|Kolossenserne|1. Thessaloniker|2. Thessaloniker|1. Timotheus|2. Timotheus|Titus|Filemon|Hebræerne|Jakob|1. Peter|2. Peter|1. Johannes|2. Johannes|3. Johannes|Judas|Åbenbaringen", "1Mo|2Mo|3Mo|4Mo|5Mo|Jos|Dom|Ru|1Sa|2Sa|1Kg|2Kg|1Kr|2Kr|Ezr|Ne|Est|Job|Sl|Ord|Præ|Høj|Esa|Jer|Kl|Eze|Da|Ho|Joe|Am|Ob|Jon|Mik|Na|Hab|Sef|Hag|Zak|Mal|Mt|Mr|Lu|Joh|ApG|Ro|1Kt|2Kt|Ga|Ef|Flp|Kol|1Ts|2Ts|1Ti|2Ti|Tit|Flm|He|Jak|1Pe|2Pe|1Jo|2Jo|3Jo|Jud|Åb"],
  fi: ["1. Mooseksen kirja|2. Mooseksen kirja|3. Mooseksen kirja|4. Mooseksen kirja|5. Mooseksen kirja|Joosua|Tuomarien kirja|Ruut|1. Samuelin kirja|2. Samuelin kirja|1. Kuninkaiden kirja|2. Kuninkaiden kirja|1. Aikakirja|2. Aikakirja|Esra|Nehemia|Ester|Job|Psalmit|Sananlaskut|Saarnaaja|Laulujen laulu|Jesaja|Jeremia|Valituslaulut|Hesekiel|Daniel|Hoosea|Joel|Aamos|Obadja|Joona|Miika|Nahum|Habakuk|Sefanja|Haggai|Sakarja|Malakia|Matteus|Markus|Luukas|Johannes|Apostolien teot|Roomalaisille|1. Korinttilaisille|2. Korinttilaisille|Galatalaisille|Efesolaisille|Filippiläisille|Kolossalaisille|1. Tessalonikalaisille|2. Tessalonikalaisille|1. Timoteukselle|2. Timoteukselle|Titukselle|Filemonille|Heprealaisille|Jaakobin kirje|1. Pietarin kirje|2. Pietarin kirje|1. Johanneksen kirje|2. Johanneksen kirje|3. Johanneksen kirje|Juudaksen kirje|Ilmestys", "1Mo|2Mo|3Mo|4Mo|5Mo|Jos|Tu|Ru|1Sa|2Sa|1Ku|2Ku|1Ai|2Ai|Esr|Ne|Est|Job|Ps|San|Sr|Lal|Jes|Jer|Va|Hes|Da|Ho|Jl|Am|Ob|Jn|Mi|Na|Hab|Sef|Hag|Sak|Mal|Mt|Mr|Lu|Joh|Ap|Ro|1Ko|2Ko|Ga|Ef|Fil|Kol|1Te|2Te|1Ti|2Ti|Tit|Flm|Hpr|Ja|1Pi|2Pi|1Jo|2Jo|3Jo|Ju|Il"],
  no: ["1. Mosebok|2. Mosebok|3. Mosebok|4. Mosebok|5. Mosebok|Josva|Dommerne|Rut|1. Samuelsbok|2. Samuelsbok|1. Kongebok|2. Kongebok|1. Krønikebok|2. Krønikebok|Esra|Nehemja|Ester|Job|Salmene|Ordspråkene|Forkynneren|Høysangen|Jesaja|Jeremia|Klagesangene|Esekiel|Daniel|Hosea|Joel|Amos|Obadja|Jona|Mika|Nahum|Habakkuk|Sefanja|Haggai|Sakarja|Malaki|Matteus|Markus|Lukas|Johannes|Apostlenes gjerninger|Romerne|1. Korinter|2. Korinter|Galaterne|Efeserne|Filipperne|Kolosserne|1. Tessaloniker|2. Tessaloniker|1. Timoteus|2. Timoteus|Titus|Filemon|Hebreerne|Jakob|1. Peter|2. Peter|1. Johannes|2. Johannes|3. Johannes|Judas|Åpenbaringen", "1Mo|2Mo|3Mo|4Mo|5Mo|Jos|Dom|Rut|1Sa|2Sa|1Kg|2Kg|1Kr|2Kr|Esr|Ne|Est|Job|Sal|Ord|For|Høy|Jes|Jer|Kla|Ese|Da|Ho|Joe|Am|Ob|Jon|Mi|Na|Hab|Sef|Hag|Sak|Mal|Mt|Mr|Lu|Joh|Apg|Ro|1Kt|2Kt|Ga|Ef|Flp|Kol|1Te|2Te|1Ti|2Ti|Tit|Flm|He|Jak|1Pe|2Pe|1Jo|2Jo|3Jo|Jud|Åp"],
  tr: ["Başlangıç|Çıkış|Levioğulları|Sayılar|Tekrar|Yeşu|Hâkimler|Rut|1. Samuel|2. Samuel|1. Krallar|2. Krallar|1. Tarihler|2. Tarihler|Ezra|Nehemya|Ester|Eyüp|Mezmurlar|Özdeyişler|Vaiz|Ezgiler Ezgisi|İşaya|Yeremya|Ağıtlar|Hezekiel|Daniel|Hoşea|Yoel|Amos|Obadya|Yunus|Mika|Nahum|Habakkuk|Tsefanya|Haggay|Zekeriya|Malaki|Matta|Markos|Luka|Yuhanna|Elçiler|Romalılar|1. Korintliler|2. Korintliler|Galatyalılar|Efesliler|Filipililer|Koloseliler|1. Selanikliler|2. Selanikliler|1. Timoteos|2. Timoteos|Titus|Filimon|İbraniler|Yakup|1. Petrus|2. Petrus|1. Yuhanna|2. Yuhanna|3. Yuhanna|Yahuda|Vahiy", "Ba|Çk|Le|Sy|Tkr|Yş|Hk|Ru|1Sa|2Sa|1Kr|2Kr|1Ta|2Ta|Ezr|Ne|Es|Ey|Mezm.|Öz|Vz|Ezg|İş|Yr|Ağ|He|Da|Ho|Yo|Ams|Ob|Yun|Mi|Na|Hb|Tsf|Hg|Zk|Ml|Mt|Mr|Lu|Yhn|Elç|Ro|1Ko|2Ko|Ga|Ef|Flp|Kl|1Se|2Se|1Ti|2Ti|Tit|Flm|İb|Yk|1Pe|2Pe|1Yh|2Yh|3Yh|Yhd|Vh"],
  zh: ["创世记|出埃及记|利未记|民数记|申命记|约书亚记|士师记|路得记|撒母耳记上|撒母耳记下|列王纪上|列王纪下|历代志上|历代志下|以斯拉记|尼希米记|以斯帖记|约伯记|诗篇|箴言|传道书|雅歌|以赛亚书|耶利米书|耶利米哀歌|以西结书|但以理书|何西阿书|约珥书|阿摩司书|俄巴底亚书|约拿书|弥迦书|那鸿书|哈巴谷书|西番雅书|哈该书|撒迦利亚书|玛拉基书|马太福音|马可福音|路加福音|约翰福音|使徒行传|罗马书|哥林多前书|哥林多后书|加拉太书|以弗所书|腓立比书|歌罗西书|帖撒罗尼迦前书|帖撒罗尼迦后书|提摩太前书|提摩太后书|提多书|腓利门书|希伯来书|雅各书|彼得前书|彼得后书|约翰一书|约翰二书|约翰三书|犹大书|启示录", "创|出|利|民|申|书|士|得|撒上|撒下|王上|王下|代上|代下|拉|尼|斯|伯|诗|箴|传|歌|赛|耶|哀|结|但|何|珥|摩|俄|拿|弥|鸿|哈|番|该|亚|玛|太|可|路|约|徒|罗|林前|林后|加|弗|腓|西|帖前|帖后|提前|提后|多|门|来|雅|彼前|彼后|约一|约二|约三|犹|启"],
  ja: ["創世記|出エジプト記|レビ記|民数記|申命記|ヨシュア|裁き人|ルツ|サムエル第一|サムエル第二|列王第一|列王第二|歴代第一|歴代第二|エズラ|ネヘミヤ|エステル|ヨブ|詩編|格言|伝道の書|ソロモンの歌|イザヤ|エレミヤ|哀歌|エゼキエル|ダニエル|ホセア|ヨエル|アモス|オバデヤ|ヨナ|ミカ|ナホム|ハバクク|ゼパニヤ|ハガイ|ゼカリヤ|マラキ|マタイ|マルコ|ルカ|ヨハネ|使徒|ローマ|コリント第一|コリント第二|ガラテア|エフェソス|フィリピ|コロサイ|テサロニケ第一|テサロニケ第二|テモテ第一|テモテ第二|テトス|フィレモン|ヘブライ|ヤコブ|ペテロ第一|ペテロ第二|ヨハネ第一|ヨハネ第二|ヨハネ第三|ユダ|啓示", "創|出|レビ|民|申|ヨシ|裁|ルツ|サ一|サ二|王一|王二|代一|代二|エズ|ネヘ|エス|ヨブ|詩|格|伝|ソロ|イザ|エレ|哀|エゼ|ダニ|ホセ|ヨエ|アモ|オバ|ヨナ|ミカ|ナホ|ハバ|ゼパ|ハガ|ゼカ|マラ|マタ|マル|ルカ|ヨハ|使徒|ロマ|コ一|コ二|ガラ|エフ|フィリ|コロ|テサ一|テサ二|テモ一|テモ二|テト|フィレ|ヘブ|ヤコ|ペ一|ペ二|ヨ一|ヨ二|ヨ三|ユダ|啓"],
  ko: ["창세기|출애굽기|레위기|민수기|신명기|여호수아|사사기|룻기|사무엘상|사무엘하|열왕기상|열왕기하|역대기상|역대기하|에스라|느헤미야|에스더|욥기|시편|잠언|전도서|솔로몬의 노래|이사야|예레미야|예레미야 애가|에스겔|다니엘|호세아|요엘|아모스|오바댜|요나|미가|나훔|하박국|스바냐|학개|스가랴|말라기|마태복음|마가복음|누가복음|요한복음|사도행전|로마서|고린도 전서|고린도 후서|갈라디아서|에베소서|빌립보서|골로새서|데살로니가 전서|데살로니가 후서|디모데 전서|디모데 후서|디도서|빌레몬서|히브리서|야고보서|베드로 전서|베드로 후서|요한 1서|요한 2서|요한 3서|유다서|요한 계시록", "창|출|레|민|신|수|삿|룻|삼상|삼하|왕상|왕하|대상|대하|라|느|더|욥|시|잠|전|아|사|렘|애|겔|단|호|욜|암|옵|욘|미|나|합|습|학|슥|말|마|막|눅|요|행|롬|고전|고후|갈|엡|빌|골|살전|살후|딤전|딤후|딛|몬|히|약|벧전|벧후|요1|요2|요3|유|계"],
  id: ["Kejadian|Keluaran|Imamat|Bilangan|Ulangan|Yosua|Hakim|Rut|1 Samuel|2 Samuel|1 Raja|2 Raja|1 Tawarikh|2 Tawarikh|Ezra|Nehemia|Ester|Ayub|Mazmur|Amsal|Pengkhotbah|Kidung Agung|Yesaya|Yeremia|Ratapan|Yehezkiel|Daniel|Hosea|Yoel|Amos|Obaja|Yunus|Mikha|Nahum|Habakuk|Zefanya|Hagai|Zakharia|Maleakhi|Matius|Markus|Lukas|Yohanes|Kisah|Roma|1 Korintus|2 Korintus|Galatia|Efesus|Filipi|Kolose|1 Tesalonika|2 Tesalonika|1 Timotius|2 Timotius|Titus|Filemon|Ibrani|Yakobus|1 Petrus|2 Petrus|1 Yohanes|2 Yohanes|3 Yohanes|Yudas|Wahyu", "Kej|Kel|Im|Bil|Ul|Yos|Hak|Rut|1Sam|2Sam|1Raj|2Raj|1Taw|2Taw|Ezr|Neh|Est|Ayb|Mz|Ams|Pkh|Kid|Yes|Yer|Rat|Yeh|Dan|Hos|Yl|Am|Ob|Yun|Mi|Nah|Hab|Zef|Hag|Za|Mal|Mat|Mrk|Luk|Yoh|Kis|Rm|1Kor|2Kor|Gal|Ef|Flp|Kol|1Tes|2Tes|1Tim|2Tim|Tit|Flm|Ibr|Yak|1Ptr|2Ptr|1Yoh|2Yoh|3Yoh|Yud|Why"],
  tl: ["Genesis|Exodo|Levitico|Bilang|Deuteronomio|Josue|Hukom|Ruth|1 Samuel|2 Samuel|1 Hari|2 Hari|1 Cronica|2 Cronica|Ezra|Nehemias|Esther|Job|Awit|Kawikaan|Eclesiastes|Awit ni Solomon|Isaias|Jeremias|Panaghoy|Ezekiel|Daniel|Oseas|Joel|Amos|Obadias|Jonas|Mikas|Nahum|Habakuk|Zefanias|Hagai|Zacarias|Malakias|Mateo|Marcos|Lucas|Juan|Gawa|Roma|1 Corinto|2 Corinto|Galacia|Efeso|Filipos|Colosas|1 Tesalonica|2 Tesalonica|1 Timoteo|2 Timoteo|Tito|Filemon|Hebreo|Santiago|1 Pedro|2 Pedro|1 Juan|2 Juan|3 Juan|Judas|Apocalipsis", "Gen|Exo|Lev|Bil|Deu|Jos|Huk|Ru|1Sa|2Sa|1Ha|2Ha|1Cr|2Cr|Ezr|Ne|Es|Job|Aw|Kaw|Ec|Sol|Isa|Jer|Pan|Eze|Dan|Os|Joe|Am|Ob|Jon|Mik|Na|Hab|Zef|Hag|Zac|Mal|Mat|Mar|Luc|Ju|Gaw|Ro|1Co|2Co|Gal|Efe|Fil|Col|1Te|2Te|1Ti|2Ti|Tit|Flm|Heb|San|1Pe|2Pe|1Ju|2Ju|3Ju|Jud|Apo"],
  vi: ["Sáng thế|Xuất Ai Cập|Lê-vi|Dân số|Phục truyền luật lệ|Giô-suê|Quan xét|Ru-tơ|1 Sa-mu-ên|2 Sa-mu-ên|1 Các vua|2 Các vua|1 Sử ký|2 Sử ký|Ê-xơ-ra|Nê-hê-mi|Ê-xơ-tê|Gióp|Thi thiên|Châm ngôn|Truyền đạo|Nhã ca|Ê-sai|Giê-rê-mi|Ai ca|Ê-xê-chi-ên|Đa-ni-ên|Ô-sê|Giô-ên|A-mốt|Áp-đia|Giô-na|Mi-chê|Na-hum|Ha-ba-cúc|Xô-phô-ni|Ha-gai|Xa-cha-ri|Ma-la-chi|Ma-thi-ơ|Mác|Lu-ca|Giăng|Công vụ|Rô-ma|1 Cô-rinh-tô|2 Cô-rinh-tô|Ga-la-ti|Ê-phê-sô|Phi-líp|Cô-lô-se|1 Tê-sa-lô-ni-ca|2 Tê-sa-lô-ni-ca|1 Ti-mô-thê|2 Ti-mô-thê|Tít|Phi-lê-môn|Hê-bơ-rơ|Gia-cơ|1 Phi-e-rơ|2 Phi-e-rơ|1 Giăng|2 Giăng|3 Giăng|Giu-đe|Khải huyền", "Sa|Xu|Lê|Dân|Phu|Gs|Qu|Ru|1Sa|2Sa|1V|2V|1Sử|2Sử|Êxr|Nê|Êxt|Gp|Th|Ch|Tr|Nhã|Ês|Giê|Ai|Êxê|Đa|Ôsê|Gê|Am|Áp|Gn|Mi|Na|Hab|Xô|Hag|Xa|Mal|Mat|Mác|Lu|Gi|Cv|Rô|1Cô|2Cô|Ga|Êph|Phl|Cô|1Tê|2Tê|1Ti|2Ti|Tít|Phlm|Hê|Gia|1Ph|2Ph|1Gi|2Gi|3Gi|Giu|Kh"],
  sw: ["Mwanzo|Kutoka|Mambo ya Walawi|Hesabu|Kumbukumbu la Torati|Yoshua|Waamuzi|Ruthu|1 Samweli|2 Samweli|1 Wafalme|2 Wafalme|1 Mambo ya Nyakati|2 Mambo ya Nyakati|Ezra|Nehemia|Esta|Ayubu|Zaburi|Methali|Mhubiri|Wimbo wa Sulemani|Isaya|Yeremia|Maombolezo|Ezekieli|Danieli|Hosea|Yoeli|Amosi|Obadia|Yona|Mika|Nahumu|Habakuki|Sefania|Hagai|Zekaria|Malaki|Mathayo|Marko|Luka|Yohana|Matendo|Waroma|1 Wakorintho|2 Wakorintho|Wagalatia|Waefeso|Wafilipi|Wakolosai|1 Wathesalonike|2 Wathesalonike|1 Timotheo|2 Timotheo|Tito|Filemoni|Waebrania|Yakobo|1 Petro|2 Petro|1 Yohana|2 Yohana|3 Yohana|Yuda|Ufunuo", "Mwa|Kut|Law|Hes|Kum|Yos|Amu|Ru|1Sa|2Sa|1Fa|2Fa|1Nya|2Nya|Ezr|Ne|Est|Ayu|Zb|Met|Mhu|Wim|Isa|Yer|Omb|Eze|Da|Ho.|Yoe|Amo|Oba|Yon|Mik|Nah|Hab|Sef|Hag|Zek|Mal|Mt|Mk|Lu|Yoh|Mdo|Ro|1Ko|2Ko|Gal|Efe|Flp|Kol|1Th|2Th|1Ti|2Ti|Tit|Flm|Ebr|Yak|1Pe|2Pe|1Yh|2Yh|3Yh|Yud|Ufu"],
  ar: ["التكوين|الخروج|اللاويين|العدد|التثنية|يشوع|القضاة|راعوث|١ صموئيل|٢ صموئيل|١ ملوك|٢ ملوك|١ أخبار الأيام|٢ أخبار الأيام|عزرا|نحميا|أستير|أيوب|المزامير|الأمثال|الجامعة|نشيد الأناشيد|إشعيا|إرميا|المراثي|حزقيال|دانيال|هوشع|يوئيل|عاموس|عوبديا|يونان|ميخا|ناحوم|حبقوق|صفنيا|حجاي|زكريا|ملاخي|متى|مرقس|لوقا|يوحنا|الأعمال|روما|١ كورنثوس|٢ كورنثوس|غلاطية|أفسس|فيلبي|كولوسي|١ تسالونيكي|٢ تسالونيكي|١ تيموثاوس|٢ تيموثاوس|تيطس|فليمون|العبرانيين|يعقوب|١ بطرس|٢ بطرس|١ يوحنا|٢ يوحنا|٣ يوحنا|يهوذا|الرؤيا", "تك|خر|لا|عد|تث|يش|قض|را|١ صم|٢ صم|١ مل|٢ مل|١ أخ|٢ أخ|عز|نح|أس|أي|مز|أم|جا|نش|إش|إر|مرا|حز|دا|هو|يوء|عا|عو|يون|مي|نا|حب|صف|حج|زك|مل|مت|مر|لو|يو|أع|رو|١ كو|٢ كو|غل|أف|في|كو|١ تس|٢ تس|١ تي|٢ تي|تي|فل|عب|يع|١ بط|٢ بط|١ يو|٢ يو|٣ يو|يه|رؤ"],
  he: ["בראשית|שמות|ויקרא|במדבר|דברים|יהושע|שופטים|רות|שמואל א׳‏|שמואל ב׳‏|מלכים א׳‏|מלכים ב׳‏|דברי הימים א׳‏|דברי הימים ב׳‏|עזרא|נחמיה|אסתר|איוב|תהלים|משלי|קהלת|שיר השירים|ישעיהו|ירמיהו|איכה|יחזקאל|דניאל|הושע|יואל|עמוס|עובדיה|יונה|מיכה|נחום|חבקוק|צפניה|חגי|זכריה|מלאכי|מתי|מרקוס|לוקס|יוחנן|מעשי השליחים|רומים|קורינתים א׳‏|קורינתים ב׳‏|גלטים|אפסים|פיליפים|קולוסים|תסלוניקים א׳‏|תסלוניקים ב׳‏|טימותיאוס א׳‏|טימותיאוס ב׳‏|טיטוס|פילימון|עברים|יעקב|פטרוס א׳‏|פטרוס ב׳‏|יוחנן א׳‏|יוחנן ב׳‏|יוחנן ג׳‏|יהודה|ההתגלות", "בר|שמ|ויק|במד|דב|יהו|שופ|רות|שמא|שמב|מלא|מלב|דהא|דהב|עזר|נחמ|אסת|איו|תה|משל|קהל|שהש|ישע|ירמ|איכ|יחז|דנ|הוש|יוא|עמו|עוב|יונ|מיכ|נחו|חבק|צפנ|חגי|זכר|מל|מתי|מר|לוק|יוח|מהש|רומ|קוא|קוב|גלט|אפס|פיל|קול|תסא|תסב|טמא|טמב|טיט|פלמ|עב|יעק|פטא|פטב|יחא|יחב|יחג|יהד|התג"],
  fa: ["پیدایش|خروج|لاویان|اعداد|تَثنیه|یوشَع|داوران|روت|۱سموئیل|۲سموئیل|۱پادشاهان|۲پادشاهان|۱تواریخ|۲تواریخ|عِزرا|نِحِمیا|اِستِر|ایّوب|مزامیر|امثال|جامعه|غزل غزل‌ها|اِشَعْیا|اِرْمیا|مراثی|حِزْقیال|دانیال|هوشَع|یوئیل|عاموس|عوبَدیا|یونِس|میکاه|ناحوم|حَبَقوق|صَفَنیا|حَجّای|زَکَریا|مَلاکی|مَتّی|مَرقُس|لوقا|یوحنا|اعمال|رومیان|۱قُرِنتیان|۲قُرِنتیان|غَلاطیان|اِفِسُسیان|فیلیپیان|کولُسیان|۱تِسالونیکیان|۲تِسالونیکیان|۱تیموتائوس|۲تیموتائوس|تیتوس|فیلیمون|عبرانیان|یعقوب|۱پِطرُس|۲پِطرُس|۱یوحنا|۲یوحنا|۳یوحنا|یهودا|مکاشفه", "پی‍|خرو|لا|اعد|تث‍|یوش‍|دا|روت|۱سم‍|۲سم‍|۱پا|۲پا|۱تو|۲تو|عز|نح‍|اس‍|ای‍|مز|ام‍|جا|غز|اش‍|ار|مرا|حز|دان‍|هو|یوئ‍|عا|عو|یون‍|می‍|نا|حب‍|صف‍|حج‍|زک‍|مل‍|مت‍|مر|لو|یو|اع‍|رو|۱قر|۲قر|غلا|اف‍|فی‍|کو|۱تس‍|۲تس‍|۱تی‍|۲تی‍|تی‍|فیل‍|عب‍|یع‍|۱پط‍|۲پط‍|۱یو|۲یو|۳یو|یه‍|مک‍"],
  ur: ["پیدائش|خروج|رُوت|1-‏سموئیل|2-‏سموئیل|1-‏سلاطین|2-‏سلاطین|1-‏تواریخ|2-‏تواریخ|عزرا|نحمیاہ|آستر|ایوب|زبور|اَمثال|واعظ|غزلُ‌الغزلات|یسعیاہ|یرمیاہ|نوحہ|حِزقی‌ایل|دانی‌ایل|ہوسیع|یُوایل|عاموس|عبدیاہ|یُوناہ|میکاہ|ناحوم|حبقّوق|متی|مرقس|لُوقا|یوحنا|اعمال|رومیوں|1-‏کُرنتھیوں|2-‏کُرنتھیوں|گلتیوں|اِفِسیوں|فِلپّیوں|کُلسّیوں|1-‏تھسلُنیکیوں|2-‏تھسلُنیکیوں|1-‏تیمُتھیُس|2-‏تیمُتھیُس|طِطُس|فِلیمون|عبرانیوں|یعقوب|1-‏پطرس|2-‏پطرس|1-‏یوحنا|2-‏یوحنا|3-‏یوحنا|یہوداہ|مُکاشفہ", "پید|خر|رُو|1سم|2سم|1سل|2سل|1تو|2تو|عز|نح|آس|ایو|زبو|اَم|وا|غز|یس|یر|نو|حِز|دا|ہو|یُوا|عا|عبد|یُون|میک|ناح|حبق|متی|مر|لُو|یوح|اع|روم|1کُر|2کُر|گل|اِفِس|فِل|کُل|1تھس|2تھس|1تیم|2تیم|طِط|فِلیم|عبر|یعق|1پط|2پط|1یوح|2یوح|3یوح|یہو|مُکا"],
}

/** Gebaute Tabellen je Sprache (deutscher Name -> Zielsprache). */
const cache = new Map<string, { voll: Map<string, string>; kurz: Map<string, string> }>()

/**
 * Zuordnungen fuer eine Sprache — leer, wenn jw.org die Sprache nicht fuehrt
 * (dann bleibt der deutsche Name stehen, wie bisher).
 */
export function buchTabelle(lang: string): { voll: Map<string, string>; kurz: Map<string, string> } {
  const fertig = cache.get(lang)
  if (fertig) return fertig
  const eintrag = ZIEL[lang]
  const voll = new Map<string, string>()
  const kurz = new Map<string, string>()
  if (eintrag) {
    const fehlen = lang === 'ur' ? new Set(UR_FEHLEN.split('|')) : null
    const deVoll = DE_VOLL.split('|').filter((b) => !fehlen?.has(b))
    const deKurz = DE_KURZ.split('|').filter((_, i) => !fehlen?.has(DE_VOLL.split('|')[i]))
    const zielVoll = eintrag[0].split('|')
    const zielKurz = eintrag[1].split('|')
    for (let i = 0; i < deVoll.length; i++) {
      voll.set(deVoll[i], zielVoll[i])
      kurz.set(deKurz[i], zielKurz[i])
    }
  }
  const gebaut = { voll, kurz }
  cache.set(lang, gebaut)
  return gebaut
}
